name: Appium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appium-test:
    runs-on: ubuntu-latest
    name: Appium Test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Specify your required .NET version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a compatible node version

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Install and Run Appium Server
        run: |
          npm install -g appium@2.0.0-beta.63
          appium driver install uiautomator2
          nohup appium &

      - name: Set up Android SDK
        run: |
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest
          echo "sdk.dir=$HOME/android-sdk" > local.properties
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        env:
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$HOME/android-sdk/emulator:$PATH

      - name: Install dependencies
        run: dotnet restore src/Gestures/Gestures.sln

      - name: Build the project
        run: dotnet build src/Gestures/Gestures.sln --configuration Release

      - name: Copy APK to working directory
        run: cp ./apk/ApiDemos-debug.apk .

      - name: Run tests
        run: dotnet test src/Gestures/Gestures.sln --logger:"trx;LogFileName=test_results.trx"
        env:
          APPIUM_HOST: 127.0.0.1
          APPIUM_PORT: 4723

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '**/*.trx'
