name: Appium .NET Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Specify your required .NET version

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Appium and Drivers
      run: |
        npm install -g appium
        appium driver install uiautomator2

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d cmdline-tools
        sudo mkdir -p /usr/local/lib/android/sdk
        sudo mv cmdline-tools /usr/local/lib/android/sdk/cmdline-tools
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3" "emulator"
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        PATH: /usr/local/lib/android/sdk/cmdline-tools/bin:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/emulator:$PATH

    - name: Install dependencies
      run: dotnet restore src/Gestures/Gestures.sln  # Specify the path to your solution file

    - name: Build the project
      run: dotnet build src/Gestures/Gestures.sln --configuration Release  # Specify the path to your solution file

    - name: Copy APK to working directory
      run: cp ./apk/ApiDemos-debug.apk .

    - name: Start Appium server
      run: appium --log-level error &
      env:
        APPIUM_HOST: 127.0.0.1
        APPIUM_PORT: 4723

    - name: Run tests
      run: dotnet test src/Gestures/Gestures.sln --logger:"trx;LogFileName=test_results.trx"  # Specify the path to your solution file
      env:
        APPIUM_HOST: 127.0.0.1
        APPIUM_PORT: 4723

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/*.trx'
